Repository VirusTrack/COVIDvu, pull requests merged in 2020-03, with the labels that each got.

#19 0018 runner from local machine
  .gitignore
  .vimrc
  docker-compose-nena.yaml
  docker-compose.yaml
  run
  run.env.SAMPLE
Labels: enhancement

#22 0021 local launch instructions
  LICENSE
  Makefile
  README.md
  docker-compose.yaml
  run
  run.env.SAMPLE
  work/COVIDvu.ipynb
  work/README.ipynb
  work/refreshdata
Labels: documentation, enhancement

#20 0006 automatic data refresh
  Makefile
  docker-compose.yaml
  run
  work/COVIDvu.ipynb
  work/README.ipynb
  work/refreshdata
Labels: enhancement

#29 0028 color separation
  work/COVIDvu.ipynb
  work/visualize.py
Labels: bug

#51 0050 fix regional identical json files
  .gitignore
  Dockerfile
  Makefile
  work/vujson.py
Labels: bug

#77 Fixed
  work/COVIDvu-US.ipynb
  work/COVIDvu.ipynb
  work/refreshdata
Labels: bug

#91 0089 fix date format bug
  work/covidvu/vudpatch.py
  work/refreshdata
Labels: bug

#95 Implented and tested
  work/covidvu/pyavka.py
  work/covidvu/vudpatch.py
  work/covidvu/vujson.py
  work/refreshdata
  work/vujson
Labels: enhancement

#129 0121 resolve bno country name conflicts
  work/covidvu/pyavka.py
  work/covidvu/vudpatch.py
  work/covidvu/vujson.py
  work/refreshdata
Labels: bug, enhancement

#140 BNO News link added
  ui/src/containers/FooterContainer.js
Labels: enhancement

#144 0097 fix cron job n venv server
  work/pyrunner
  work/refreshdata
  work/refreshdata.config.SAMPLE
  work/vujson
Labels: bug

#154 Implemented and tested
  work/refreshdata
Labels: Done, bug

#157 Implemented and tested
  work/covidvu/pipeline/jsonpack.py
  work/jsonpack
  work/resources/test_pipeline/test-global.json
Labels: Done

#160 Add nbstripout pre-commit hook
  work/.pre-commit-config.yaml
  work/requirements.txt
Labels: enhancement

#161 135 refresh auto update latest
  ui/public/index.html
  ui/src/components/Graph.js
  ui/src/constants/index.js
  ui/src/containers/FooterContainer.js
  ui/src/containers/GlobalGraphContainer.js
  ui/src/containers/StatsContainer.js
  ui/src/containers/USGraphContainer.js
  ui/src/containers/USRegionsGraphContainer.js
  ui/src/ducks/services.js
  ui/src/hooks/ui.js
  ui/src/services.js
Labels: Done

#164 0148 covidvu makefile
  CONTRIBUTORS.md
  work/Makefile
  work/covidvu/pipeline/vucounty.py
  work/modulename.txt
  work/setup.py
  work/test/covidvu/pipeline/test_vucounty.py
  work/test/covidvu/pipeline/test_vujson.py
  work/version.txt
Labels: Done

#172 RC1 - Patching the states again in real-time
  work/covidvu/pipeline/vudpatch.py
  work/covidvu/pipeline/vujson.py
  work/diagnostics/global-data-diagnostics.ipynb
  work/experiments/virustrack_live-validation-tests.ipynb
  work/version.txt
Labels: Done

#174 0162 test vujson
  work/COVIDvu-US.ipynb
  work/COVIDvu-predict.ipynb
  work/COVIDvu-stats.ipynb
  work/COVIDvu.ipynb
  work/covidvu/pipeline/vujson.py
  work/covidvu/predict.py
  work/diagnostics/global-data-diagnostics.ipynb
  work/figures/.gitkeep
  work/figures/United Kingdom_log_prediction.png
  work/resources/test_COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
  work/resources/test_COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv
  work/resources/test_COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv
  work/test/covidvu/pipeline/test_vujson.py
Labels: Done

#181 0180 privacy policy source
  CONTRIBUTORS.md
  TopReferrers-2020-03-18-21-43-28.csv
  resources/COVIDvu-FB-cover.jpg
  resources/COVIDvu-FB-cover.psd
  resources/privacy-policy.html
  work/COVIDvu-predict.ipynb
  work/covidvu/pipeline/vudpatch.py
  work/covidvu/pipeline/vuregions.py
  work/resources/pipeline.graffle
Labels: Done

#188 0147-continental-groupings - implemented
  .gitignore
  CONTRIBUTORS.md
  TopReferrers-2020-03-18-21-43-28.csv
  resources/COVIDvu-FB-cover.psd
  work/Makefile
  work/covidvu/pipeline/vuregions.py
  work/refreshdata
  work/resources/pipeline.graffle
  work/resources/test_pipeline/confirmed.json
  work/test/covidvu/pipeline/test_vuregions.py
  work/vuregions
Labels: Done, enhancement

#198 0196-Implement-all-continental-regions - complete
  work/covidvu/pipeline/vuregions.py
  work/pytest.ini
  work/test/covidvu/pipeline/test_vuregions.py
Labels: Done, high

#199 0166-pre-commit instructions and cell
  work/README.ipynb
Labels: Done

#203 Data feed fixed - changes to BNO data source
  CONTRIBUTORS.md
  work/covidvu/pipeline/vudpatch.py
  work/pyavka
  work/refreshdata
Labels: Done

#205 RC1 - resolved
  work/covidvu/pipeline/pyavka.py
  work/exclude.rclone
  work/refreshdata
Labels: Done

#208 0207 hospital beds
  work/covidvu/pipeline/vuhospitals.py
  work/covidvu/pipeline/vujson.py
  work/covidvu/predict.py
  work/pytest.ini
  work/resources/pipeline-20200320.png
  work/resources/pipeline.graffle
  work/test/covidvu/pipeline/test_vuhospitals.py
  work/test/covidvu/pipeline/test_vujson.py
Labels: question

#213 RC1 - hospital beds count
  resources/hospital-beds-count-US-20200320.json
  work/covidvu/pipeline/jsonpack.py
  work/covidvu/pipeline/vuhospitals.py
  work/refreshdata
  work/refreshdata.config.SAMPLE
  work/resources/hospital-beds-count-US-20200320.json
  work/resources/test_pipeline/hospital-beds-count-US.json
  work/resources/test_pipeline/test-US.json
  work/resources/test_pipeline/test-global.json
  work/test/covidvu/pipeline/test_jsonpack.py
  work/test/covidvu/pipeline/test_vuhospitals.py
  work/test/covidvu/pipeline/test_vuregions.py
  work/version.txt
Labels: Done

#221 RC1 - tested on staging
  DATASOURCES.md
  README.md
  work/countyraid
  work/covidvu/pipeline/jsonpack.py
  work/refreshdata
  work/resources/counties-US-all-20200320.json
  work/resources/test_pipeline/counties-US-all.json
  work/resources/test_pipeline/test-US.json
  work/test/covidvu/pipeline/test_jsonpack.py
  work/version.txt
Labels: Done

#229 0223 refreshdata hosts virtualenv
  work/deprecated/jsonpack
  work/deprecated/pyavka
  work/deprecated/vudpatch
  work/deprecated/vujson
  work/deprecated/vuregions
  work/refreshdata
Labels: Done, enhancement

#226 Implemented, tested, and deployed
  Makefile
  dockerimagename.txt
  dockerimageversion.txt
  work/deprecated/jsonpack
  work/deprecated/pyavka
  work/deprecated/vudpatch
  work/deprecated/vujson
  work/deprecated/vuregions
  work/refreshdata
Labels: Done

#262 0261 implement jupyter pre commit hooks
  Dockerfile
  dockerimageversion.txt
Labels: Done

#283 Implemented and tested
  .gitignore
  CONTRIBUTORS.md
  work/countyraid
  work/covidvu/pipeline/vucounty.py
  work/experiments/countyraid.ipynb
  work/refreshdata
  work/resources/counties-US-all-20200320.json
  work/resources/test_pipeline/counties-US-CSBS.json
  work/test/covidvu/pipeline/test_vucounty.py
  work/version.txt
Labels: Done

#303 0302 csbs exp dev07 broke counties feed
  DATASOURCES.md
  Dockerfile
  resources/background-image.jpeg
  work/countyraid
  work/covidvu/pipeline/vucounty.py
  work/experiments/countyraid.ipynb
  work/refreshdata
Labels: Done

#308 Fixed - vucounty module ready
  work/countyraid
  work/covidvu/pipeline/vucounty.py
  work/resources/curl-cacert.pem
Labels: Done

#324 RC1 -- ready to test in staging
  .gitignore
  work/Makefile
  work/countyraid
  work/covidvu/pipeline/jsonpack.py
  work/covidvu/pipeline/vuhospitals.py
  work/refreshdata
  work/resources/hospital-beds-count-US-20200320.json
  work/resources/test_pipeline/test-US.json
  work/test/covidvu/test_covidvu.py
  work/version.txt
Labels: Done

#327 RC1 - fixed
  work/covidvu/pipeline/vujson.py
Labels: Done

#333 0321 csse bno homologize names
  work/covidvu/pipeline/vudpatch.py
  work/covidvu/pipeline/vujson.py
  work/gcm
Labels: Done

#344 "0331 - Implemented and tested against local and staging"
  work/Makefile
  work/covidvu/pipeline/jsonpack.py
  work/test/covidvu/pipeline/test_jsonpack.py
Labels: Done

#343 "0335 - Ready minor issues addressed"
  work/Makefile
  work/covidvu/pipeline/jsonpack.py
  work/diagnostics/global-data-diagnostics.ipynb
  work/test/covidvu/pipeline/test_jsonpack.py
Labels: Done

#350 0349 bno broke the feed
  work/Makefile
  work/covidvu/pipeline/pyavka.py
  work/covidvu/predict.py
  work/experiments/countyraid.ipynb
  work/requirements.txt
Labels: Done

#353 "0352 - Fixed - #352"
  .gitignore
  work/covidvu/pipeline/jsonpack.py
  work/covidvu/pipeline/pyavka.py
  work/refreshdata
Labels: Done

#360 "0339 - Ready - fixes #339 - no bare metal server support"
  DATASOURCES.md
  work/covidvu/pipeline/jsonpack.py
  work/resources/test_pipeline/prediction-conf-int-UnitedKingdom.json
  work/resources/test_pipeline/prediction-mean-UnitedKingdom.json
  work/test/covidvu/pipeline/test_jsonpack.py
Labels: Done

#376 0351 bno tables auto selection
  work/Makefile
  work/covidvu/pipeline/pyavka.py
  work/pyavka
  work/refreshdata
  work/resources/test_pipeline/table-AA.html
  work/resources/test_pipeline/table-BB.html
  work/resources/test_pipeline/table-CC.html
  work/test/covidvu/pipeline/test_pyavka.py
Labels: Done

#382 0381 us individual states predictions
  work/covidvu/pipeline/jsonpack.py
  work/covidvu/predict.py
  work/crystalball
  work/jsonpack
  work/resources/test_pipeline/prediction-world-conf-int-UnitedKingdom.json
  work/resources/test_pipeline/prediction-world-mean-UnitedKingdom.json
  work/resources/test_site_data/test-predictions/confirmed-US-Regions.json
  work/resources/test_site_data/test-predictions/confirmed-US.json
  work/resources/test_site_data/test-predictions/prediction-conf-int-US.json
  work/resources/test_site_data/test-predictions/prediction-world-conf-int-Albania.json
  work/resources/test_site_data/test-predictions/prediction-world-conf-int-Algeria.json
  work/resources/test_site_data/test-predictions/prediction-world-conf-int-Argentina.json
  work/resources/test_site_data/test-predictions/prediction-world-conf-int-Italy.json
  work/resources/test_site_data/test-predictions/prediction-world-conf-int-US.json
  work/resources/test_site_data/test-predictions/prediction-world-mean-Albania.json
  work/resources/test_site_data/test-predictions/prediction-world-mean-Algeria.json
  work/resources/test_site_data/test-predictions/prediction-world-mean-Argentina.json
  work/resources/test_site_data/test-predictions/prediction-world-mean-Italy.json
  work/resources/test_site_data/test-predictions/prediction-world-mean-US.json
  work/test/covidvu/pipeline/test_jsonpack.py
  work/test/covidvu/test_predict.py
Labels: Done

#387 0381 us individual states predictions
  work/covidvu/pipeline/jsonpack.py
  work/jsonpack
  work/test/covidvu/pipeline/test_jsonpack.py
  work/test/covidvu/test_predict.py
Labels: Done

#389 0347 silent conda docker update
  CONTRIBUTORS.md
  Dockerfile
  dockerimageversion.txt
Labels: Done

#393 "0391 - test environment support - done #391"
  work/refreshdata
Labels: Done

#395 "0390 - Implemented and tested"
  .gitignore
  dockerimageversion.txt
  work/refreshdata
  work/version.txt
Labels: Done

#402 0390 tactical data snapshots
  work/covidvu/pipeline/jsonpack.py
  work/resources/test_site_data/test-predictions/confirmed-US-Regions.json
  work/resources/test_site_data/test-predictions/confirmed-US.json
  work/test/covidvu/pipeline/test_jsonpack.py
Labels: Done

#403 staging
  work/covidvu/pipeline/jsonpack.py
  work/pyrunner
  work/test/covidvu/pipeline/test_jsonpack.py
Labels: Done

#418 "0415 - Fixed #415 - CrystalBall and snapshots enabled"
  work/refreshdata
Labels: Done

#427 0076 notebook crashes
  work/COVIDvu-US.ipynb
  work/COVIDvu-predict.ipynb
  work/COVIDvu-stats.ipynb
  work/COVIDvu.ipynb
  work/README.ipynb
  work/covidvu/predict.py
  work/covidvu/visualize.py
  work/pyrunner
  work/refreshdata
  work/refreshdata.config.SAMPLE
  work/test/covidvu/test_predict.py
Labels: Done, bug, enhancement
